apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota-test
  namespace: ivolve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quota-test
  template:
    metadata:
      labels:
        app: quota-test
    spec:
      containers:
        - name: nginx
          image: nginx:alpine