apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo 'hello from pvc-test-pod' >> /app-logs/test.log && sleep 3600"]
      volumeMounts:
        - name: app-logs
          mountPath: /app-logs
  volumes:
    - name: app-logs
      persistentVolumeClaim:
        claimName: app-logs-pvc